apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    env: {{ .Values.global.env }}
    product: {{ .Values.global.projectName | lower }}
    app: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  type: NodePort
  ports:
    - name: application
      port: {{ .Values.containerPort | int }}
      nodePort: 30080
      targetPort: {{ .Values.containerPort | int }}
      protocol: TCP
